### ISSUE TITLE
Error Message Api

### ISSUE THREAD

**Issue by dlupu** [trailblazer/reform#345]
Hello

According to the [documentation](http://trailblazer.to/gems/reform/#api)  `#errors returns validation messages in a classic ActiveModel style``

This does not seem to be completely true when using Dry Validations. 

For instance `errors.full_messages` will generate `NoMethodError: undefined method 'full_messages' for #<Reform::Contract::Errors:0x007fecf8c3f798 @errors={}>`

Same happens for `errors.full_message_for(:attribute)`. 

SInce reform is planning to drop support for Active Model Validations, I think that providing a stable errors API would facilitate the migration to dry validations. WDYT ?  

BR
Dorian

**Comment by jesseiqmi** [comment]
Agreed and more so to the point that I just finished running the gauntlet on getting Reform implemented and now just fine tuning my first form that uses a collection and now dealing with errors being displayed back to the user.  I'm using `reform` and `reform-rails` 2.1 with Rails 4.2.x. 

When I drop in a custom validator for the collection and using `errors.add(:something, 'at least one is required)` it gets added first, then as the rest of the reform validations kick in they get added afterwards.

Example:
```ruby
property :title
property :date

validates :title, presence: true
validates :date, presence: true
validate :validate_at_least_one_foo

collection :foos do
  property :thing1
  property :thing2
end

def validate_at_least_one_foo
  errors.add(:foos, 'at least one is required') if foos.size == 0
end
```

Errors as displayed to user if all are triggered:

* Foos - at least one is required
* Thing 1 - is required
* Thing 2 - is required

Any thoughts on how we can control the display order of errors?  Ideally, as this deals with a collection of 'foos' at the bottom of the UI page, its order in the error messages as displayed to the user should appear last, not first so that they can address issues from the top of the page first and work down.

FYI I jumped on to this ticket as the behavior is different from Rails handling of errors - I can created a new ticket if better?

Cheers and thanks!

**Comment by dlupu** [comment]
@jesseiqmi I think you should have created a new ticket, we're not speaking about the same problem.

**Comment by jesseiqmi** [comment]
Thanks @dlupu after rereading you're specifically talking about dry-validations.

I've moved this out to its own ticket https://github.com/apotonick/reform/issues/351

**Comment by apotonick** [comment]
The `Errors` API with dry-v is still subject to change, it'll be compatible with the one we have now!

**Comment by fran-worley** [comment]
This is not actually an issue with Reform itself. At the moment Dry-Validation doesn't differentiate between `messages` ("can't be blank") and `full_messages` ("user_name can't be blank"). There is simply one error method that provides you with either your custom message, or the standard message in 'full' format.

Because of this, I decided to create custom error messages for each validation and can then access the messages for a specific attribute using:

```ruby
@form.errors[:attribute]
```
It won't help if you need to be able to get both `message` and `full_message` for a single attribute but otherwise this should solve your problem.

I know the dry-v team are looking at enhancements for the error message API in future versions so I suggest that you raise your issue there if you want to see it get addressed.

**Comment by apotonick** [comment]
I think it's fine to discuss here as it probably makes sense to coordinate the API with the dry-v guys?!

**Comment by fran-worley** [comment]
Just been looking into this again and full messages are now possible with dry-validations. @apotonick to support this you'd need to change this line:
https://github.com/apotonick/reform/blob/master/lib/reform/form/dry.rb#L38
to pass `:full` to the messages call. 

If @dlupu this is something you still need we could support it by enabling a config setting on the validation group or something.
e.g.
```ruby
validation :default, errors: :full do
 # some dry-v code here...
end
```

**Comment by activefx** [comment]
What's the recommended API for nested error messages? 

Right now, Reform is returning this structure for a has one relationship: 
```
{:email_address=>[[:email, ["is missing", "must be a valid format"]]]}
```

And while 
```
@form.errors[:attribute]
```
is great for accessing and displaying top level validation errors, I don't see a straightforward way to do that for nested validation errors. Any thoughts would be appreciated.

**Comment by fran-worley** [comment]
@activefx this is covered here #389

**Comment by fran-worley** [comment]
On second thoughts, we are going to have to expand the reform error API to add this correctly as with validations in a collection dry won't return the correct nested key. We will just add the active record style full_message methods to the errors object. If anyone wants to give this a go PRs are welcome!

**Comment by fran-worley** [comment]
So Reform 2.3.0 will provide a new Errors API to mirror that provided by dry-v 0.10.0 onwards.

The API will look something like this:

```ruby
form.messages(options) # => returns hints and errors
form.errors(options) # => returns just errors
form.hints(options) # => returns just hints
```

Supported options are as per the dry-validation API:
```ruby
:local # for translations
:full # to return messages including the attribute name i.e. "email must be filled"
```

**Comment by apotonick** [comment]
Dope!

I'm just wondering whether we should have an error object for that which exposes the three new methods instead of stuffing them all into `Form`?

**Comment by fran-worley** [comment]
So you'd end up with form.error.errors?

**Comment by apotonick** [comment]
The idea is to work towards an API such as

```ruby
result = form.validate(..)
```

where the errors are no longer kept in the form, and where the API prevents you from calling `validate` twice (I still don't know exactly how to nicely provide that, though), so a decoupled layer for all kinds of visual logic would be better.

**Comment by dnd** [comment]
`#errors` could be left for backwards compat if desired, and validation results could instead be placed into a `#validation_results` method or something. Then you get `form.validation_results.errors` `form.validation_results.hints`, `form.validation_results.raw`

**Comment by dnd** [comment]
For me, ideally a response would look like the example I linked in #410. I know some of that isn't available yet from dry-validation such as the individual tokens, or being able to get errors for a collection, and its children at the same time, but the general structure gives everything. 

I understand that it is way more than most need, so I would be happy if the raw validation result was exposed so that I could do whatever I want with it.

**Comment by apotonick** [comment]
This thread is completely useless because everyone just yells what they want, but not what it should look like, not a single proper specification of our future errors API. I'm closing this as I find it very frustrating.
